### PR TITLE
Add article page

### PR DESCRIPTION
**Pull request by sanadwj**
## What this PR does

-Adds the article view page

## Screenshot 

image

### CODE REVIEW

**Comment by krys2fa** [comment]
### Good job on the project @sanadwj and @pbkabali 👏 
You made good use of semantic HTML and utilized CSS best practices 💪  
Your repo also has a professional README file and good use of git commit messages 🌟 

### Status: Changes Required ♻️ 
There is just one thing to fix and that is the horizontal scroll bar at the bottom of the page. 
Kindly work on this and request another code review.

Happy Coding 💻 😄 
Chris Amanor (Slack)

**Comment by pbkabali** [comment]
Thanks so much, @krys2fa. We have worked on the feedback and resubmitted the review request.

**Comment by ikraamg** [comment]
### **Status: PROJECT APPROVED**  :1st_place_medal: :1st_place_medal: :1st_place_medal:


Hi @pbkabali and @sanadwj   :smile:  Congratulations, your project looks amazing and you did an amazing job making the necessary change :sunglasses:.
You can merge and submit your project! 

If you have any questions, don't hesitate to contact me through slack, my handle is: @**_ikraam_**


_**Happy coding and good luck on the next project**_  :desktop_computer: 

_Project reviewed by Ikraam Ghoor @ikraamg (TSE)_

**Comment by pbkabali** [comment]
Thanks, @ikraamg for your time to review our work

**Pull request merged**
